### ISSUE TITLE
need_count throws warning with sphinx-needs 1.0.1

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-needs#672] opened 2022-08-20 15:47 UTC
If a filter with an own `needs_extra_option` is used within `need_count`, a warning a thrown. The output is however created correctly. This was not the cases with 0.7.9.

Example:

```
Number of System Requirements: :need_count:`type=='req-sys'`
Number of ASIL D Requirements: :need_count:`asil=='D'`
```

Throws

> WARNING: Filter asil=='D' not valid: Error: Filter asil=='D' not valid: Error: name 'asil' is not defined

The first filter with `type` throws no warning.

**Comment by haiyangToAI** [comment] 2022-08-24 07:59
Hi @twodrops,

I tried  `needs_extra_options` with `need_count`, but no warnings are thrown.

In your example above, is the extra option `asil` defined in `needs_extra_options` in `conf.py`, e.g. `needs_extra_options=["asil"]`?

If so, I need more info to analyze. Could you please provide a minimal example that can reproduce the warning?

**Comment by twodrops** [comment] 2022-08-24 08:30
@haiyangToAI That's right `asil` is a `needs_extra_option`. I migrated the project from 0.7.9 to 1.0.1 and this warning appeared. 
The project is an internal one to which you have access. I will send you the link via email.

Thanks for checking this out.

**Comment by haiyangToAI** [comment] 2022-09-02 08:37
Hi @twodrops,

After analyzing the documents you mentioned, I found the reason why those warnings appear.

First of all, it might seems those warnings are caused by `need_count`, but it actually has nothing to do with it.

The warnings are legit. From the warning example above, it suggests that the filter string `asil=='D'` failed the evaluation, because extra option `asil` is not defined.

This made me wonder why extra option `asil` is not defined in certain needs. Then I went through the documentation, I found the usage of directive [`test-file`](https://sphinx-test-reports.readthedocs.io/en/latest/directives/test_file.html#usage).

 [`test-file`](https://sphinx-test-reports.readthedocs.io/en/latest/directives/test_file.html#usage) is the real issue causing all this. It seems to me, directive [`test-file`](https://sphinx-test-reports.readthedocs.io/en/latest/directives/test_file.html#usage) doesn't consider `needs_extra_options`, that's why those extra options are not added into needs introduced by `test-file`.

To fix this, please open a ticket at repo [sphinx-test-reports](https://github.com/useblocks/sphinx-test-reports).

**Comment by haiyangToAI** [comment] 2022-09-02 08:50
https://github.com/useblocks/sphinx-test-reports/issues/41

**Comment by twodrops** [comment] 2022-09-02 14:19
@haiyangToAI Thanks for analysing this and finding out the root cause. Also thanks for creating the issue.

**Comment by danwos** [comment] 2022-09-06 06:54
I close this issue as it is no problem for Sphinx-Needs and gets solved here: https://github.com/useblocks/sphinx-test-reports/issues/41

**Closed by danwos** 2022-09-06 06:54 UTC
